server:
  port: 8083

spring:
  application:
    name: project-service
  datasource:
    url: jdbc:mysql://localhost:3306/ProjectDB
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always #앱 실행 시 DB 초기화를 진행하는 역할. data.sql의 작동을 돕는다
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/