server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ProjectDB
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
